version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  buildtest:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: .[test]
          pip-dependency-file: setup.py
          pkg-manager: pip-dist
      - run:
          command: |
            pytest tests
          name: Test

workflows:
  main:
    jobs:
      - buildtest
